#!/bin/bash

# OpenWork Test Setup Script
# This script helps set up the test target in Xcode

echo "======================================"
echo "OpenWork Test Target Setup"
echo "======================================"
echo ""
echo "To add the test target to your Xcode project:"
echo ""
echo "1. Open OpenWork.xcodeproj in Xcode"
echo ""
echo "2. Add Test Target:"
echo "   - File → New → Target..."
echo "   - Select 'Unit Testing Bundle'"
echo "   - Product Name: OpenWorkTests"
echo "   - Target to be Tested: OpenWork"
echo "   - Click 'Finish'"
echo ""
echo "3. Add Existing Test Files:"
echo "   - Right-click on OpenWorkTests group in Project Navigator"
echo "   - Select 'Add Files to OpenWorkTests...'"
echo "   - Navigate to OpenWorkTests folder"
echo "   - Select all .swift test files:"
echo "     - VMManagerTests.swift"
echo "     - TaskManagerTests.swift"
echo "     - ProviderManagerTests.swift"
echo "     - MCPManagerTests.swift"
echo "     - KeychainManagerTests.swift"
echo "     - SkillRegistryTests.swift"
echo "     - ConnectorRegistryTests.swift"
echo "     - VMSnapshotManagerTests.swift"
echo "   - Ensure 'Copy items if needed' is UNCHECKED"
echo "   - Ensure target 'OpenWorkTests' is checked"
echo "   - Click 'Add'"
echo ""
echo "4. Delete auto-generated test file (if created):"
echo "   - Xcode may create OpenWorkTests.swift automatically"
echo "   - Delete it if it exists (we have our own test files)"
echo ""
echo "5. Build and Run Tests:"
echo "   - Product → Test (⌘U)"
echo "   - Or use Test Navigator (⌘6)"
echo ""
echo "======================================"
echo "Test Files Location:"
echo "======================================"
echo ""

# List test files
TEST_DIR="$(dirname "$0")/OpenWorkTests"
if [ -d "$TEST_DIR" ]; then
    echo "Found test files in $TEST_DIR:"
    ls -la "$TEST_DIR"/*.swift 2>/dev/null || echo "No Swift files found"
else
    echo "Test directory not found at expected location"
fi

echo ""
echo "======================================"
echo "Running Tests from Command Line:"
echo "======================================"
echo ""
echo "After adding the test target, you can run tests with:"
echo ""
echo "  xcodebuild test \\"
echo "    -project OpenWork.xcodeproj \\"
echo "    -scheme OpenWork \\"
echo "    -destination 'platform=macOS'"
echo ""
echo "Or for specific test class:"
echo ""
echo "  xcodebuild test \\"
echo "    -project OpenWork.xcodeproj \\"
echo "    -scheme OpenWork \\"
echo "    -destination 'platform=macOS' \\"
echo "    -only-testing:OpenWorkTests/VMManagerTests"
echo ""
